### ISSUE TITLE
import-module dbachecks fails with offline install

### ISSUE THREAD

**Issue by jeffjacobs0** [sqlcollaborative/dbachecks#484]
On a 2012 R2 server running SQL 2014 with no internet access, I used the Save-Modules of Pester, dbatools, PSFramework, and dbachecks. Using import-module failed with this error:

PS C:\Windows\system32> import-module PSFramework
PS C:\Windows\system32> import-module dbatools
PS C:\Windows\system32> import-module Pester
PS C:\Windows\system32> import-module dbachecks
Exception calling "InvokeScript" with "4" argument(s): "Method invocation failed because [System.String] does not contain a method named 'foreach'."
At C:\Users\ux0msp02\Documents\WindowsPowerShell\Modules\dbachecks\dbachecks.psm1:11 char:12
+     else { $ExecutionContext.InvokeCommand.InvokeScript($false, ([scriptblock]:: ...
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : RuntimeException

Versions are:
Pester 4.3.1
PSFramework 0.9.18.52
dbatools 0.9.336
dbachecks 1.1.132

$PSVersionTable is
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.18968
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

Some notes on my process:
1. The computer I ran Save-Module on was running PS 5.1.14393.2189, Build 10.0.14393.2189, PSRemotingProtocol 2.3, same everything else
2. I moved the folders to C:\Users\username\Documents\WindowsPowerShell\Modules
3. I had to move the modules up one folder level from their version number to have PS install them, e.g Modules\dbachecks\1.1.132\*.* -> Modules\dbachecks\*.*
4. Security is locked down pretty tight on these servers
5. Repeating import-module dbachecks returns without error, but fails to complete the installation (I think. Get-DbcCheck fails with not finding "...AppData\Local\dbachecks\checks.json'")

**Comment by SQLDBAWithABeard** [comment]
Which version have you saved?

Could you run $error[0] | fl - force and put the expanded error in here.

**Comment by jeffjacobs0** [comment]
It was the 1.1.132 version saved from the PowerShell gallery. 

Exception
System.Management.Automation.MethodInvocationException: Exception calling "InvokeScript" with "4" argument(s): "Method invocation failed because
[System.String] does not contain a method named 'foreach'." ---> System.Management.Automation.RuntimeException: Method invocation failed because
[System.String] does not contain a method named 'foreach'.
at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(ScriptBlock sb, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)
at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(Boolean useLocalScope, ScriptBlock scriptBlock, IList input, Object[] args)
at CallSite.Target(Closure , CallSite , Object , Boolean , Object , Object , Object )
--- End of inner exception stack trace ---
at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
at CallSite.Target(Closure , CallSite , Object , Boolean , Object , Object , Object )
at System.Management.Automation.Interpreter.DynamicInstruction`6.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : RuntimeException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Import-ModuleFile, C:\Users\ux0msp02\Documents\WindowsPowerShell\Modules\dbachecks\dbachecks.psm1: line 11
                        at <ScriptBlock>, C:\Users\ux0msp02\Documents\WindowsPowerShell\Modules\dbachecks\dbachecks.psm1: line 34
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :

**Comment by SQLDBAWithABeard** [comment]
OK, so all the only ForEach methods I can see are the ones in New-Json. Could you replace line 49 in New-Json

````@($configs).foreach{$config += "$_ "}````

and see if that works for you and if it does I will update

**Comment by jeffjacobs0** [comment]
Okay that fixed that one. Once that was unblocked I started getting this:

System.Management.Automation.MethodInvocationException: Exception calling "InvokeScript" with "4" argument(s): "Invalid array passed in, ']' expected.
(1): [" ---> System.Management.Automation.CmdletInvocationException: Invalid array passed in, ']' expected. (1): [ ---> System.ArgumentException: Invalid array passed in, ']' expected. (1): [
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeList(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

But I traced that to New-Json.ps1 line:
$Descriptions = Get-Content $ModuleRoot\internal\configurations\DbcCheckDescriptions.json | ConvertFrom-Json

I think the $ModuleRoot was giving it issue. I replaced it with:
".\internal\configurations\DbcCheckDescriptions.json"

and everything installed with out error.

**Comment by kylejdoyle** [comment]
Commenting to confirm that I was having the same issue and resolved by following these steps.

Made the following changes to New-Json.ps1.

1. Replace line 49 with `@($configs).foreach{$config += "$_ "}`
2. Replace line 87 with `$Descriptions = Get-Content '.\internal\configurations\DbcCheckDescriptions.json' | ConvertFrom-Json`

**Comment by wsmelton** [comment]
@kylejdoyle // @jeffjacobs0 

I'm not at a computer to test but you should be able to update to the following on line 87:

`"$script:ModuleRoot\internal\configurations\DbcCheckDescriptions.json' | ConvertFrom-Json`

We set `$ModuleRoot` as a global variable and it looks like it just got missed referencing it properly. It is referenced as a global variable in this manner everywhere else.
